#!/usr/bin/env bash
#
# Runs ON THE BOX, unpacked from the artifact. Not run from a laptop.
#
# The instance has NO PORT 22 by design (sg-0b19531290e391e17 is 80/443 only),
# so there is no scp and no rsync. Everything arrives via S3 + SSM — see
# deploy/push.sh. That constraint is deliberate: it is also what makes a
# careless `rsync repo-root /var/www` impossible.
#
# Idempotent. Safe to re-run.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REGION="${AWS_REGION:-ap-south-1}"

echo "==> Installing Quadis-go $(cat "$HERE/VERSION" 2>/dev/null || echo unknown)"

# --- service user ---------------------------------------------------------
if ! id quadis >/dev/null 2>&1; then
  useradd --system --home /opt/quadis --shell /sbin/nologin quadis
fi

# --- frontend -------------------------------------------------------------
mkdir -p /var/www/quadis
# --delete so a removed asset actually disappears, rather than lingering and
# being served forever alongside its replacement.
rsync -a --delete "$HERE/www/" /var/www/quadis/
chown -R root:root /var/www/quadis
find /var/www/quadis -type d -exec chmod 755 {} + -o -type f -exec chmod 644 {} +

# --- backend --------------------------------------------------------------
mkdir -p /opt/quadis/api /opt/quadis/api/uploads
# --delete would take uploads with it, so exclude it.
rsync -a --delete --exclude uploads "$HERE/api/" /opt/quadis/api/
[ -f /opt/quadis/api/server ] && chmod 755 /opt/quadis/api/server

# If legacy package.json exists, install dependencies; otherwise Go binary is self-contained.
if [ -f /opt/quadis/api/package.json ]; then
  echo "==> Installing production dependencies (npm-20)"
  ( cd /opt/quadis/api && /usr/bin/npm-20 ci --omit=dev --no-audit --no-fund ) \
    || ( cd /opt/quadis/api && /usr/bin/npm-20 install --omit=dev --no-audit --no-fund )
fi

chown -R quadis:quadis /opt/quadis

# --- secrets --------------------------------------------------------------
# Read from SSM Parameter Store at deploy time and written to a root-owned
# 0640 file. NOTHING here comes from the repo: the published test fixtures
# carry a dev ADMIN_PIN, and seeding production from them would put a
# world-readable value in front of guest booking records.
#
# The instance role (quadis-app-ec2) can read /quadis/* and nothing else.
mkdir -p /etc/quadis
umask 077

get_param() {
  aws ssm get-parameter --name "$1" --with-decryption \
      --region "$REGION" --query 'Parameter.Value' --output text 2>/dev/null || true
}

DB_PASS="$(get_param /quadis/db-password)"
if [ -z "$DB_PASS" ]; then
  echo "FATAL: /quadis/db-password not readable from SSM" >&2
  exit 1
fi

# Written fresh each deploy so a rotated parameter takes effect on restart.
{
  echo "# Generated by deploy/install.sh — do not edit, next deploy overwrites."
  echo "DATABASE_URL=postgres://quadis:${DB_PASS}@127.0.0.1:5432/quadis"
  echo "AWS_REGION=${REGION}"
  echo "IMAGE_BUCKET=quadis-hotel-photos"
  for p in SESSION_SECRET ADMIN_PIN ADMIN_PASSWORD \
           RAZORPAY_KEY_ID RAZORPAY_KEY_SECRET RAZORPAY_WEBHOOK_SECRET \
           GROQ_API_KEY GROQ_API_KEYS GEMINI_API_KEY GEMINI_API_KEYS META_WHATSAPP_TOKEN META_PHONE_NUMBER_ID \
           META_OWNER_PHONE OWNER_WHATSAPP_PHONE CORS_ORIGIN IMAGE_PUBLIC_URL \
           RESAVENUE_OTA_USERNAME RESAVENUE_OTA_PASSWORD RESAVENUE_OTA_ID_CONTEXT \
           RESAVENUE_PUSH_URL RESAVENUE_PUSH_AUTHORIZATION RESAVENUE_TARGET; do
    v="$(get_param "/quadis/$(echo "$p" | tr 'A-Z_' 'a-z-')")"
    [ -n "$v" ] && echo "$p=$v"
  done
} > /etc/quadis/api.env

chown root:quadis /etc/quadis/api.env
chmod 640 /etc/quadis/api.env

# SESSION_SECRET is load-bearing, not optional. backend/src/lib/auth.ts returns
# null for it under NODE_ENV=production, which means the app refuses to issue
# any session at all rather than falling back to the dev secret that is
# published in the repo. Fail here, visibly, instead of on a guest's login.
if ! grep -q '^SESSION_SECRET=' /etc/quadis/api.env; then
  echo "FATAL: /quadis/session-secret missing from SSM." >&2
  echo "       Create it first:" >&2
  echo "       aws ssm put-parameter --name /quadis/session-secret --type SecureString \\" >&2
  echo "         --value \"\$(openssl rand -base64 48)\" --region $REGION" >&2
  exit 1
fi

# Payments are all-or-nothing. A key without a webhook secret is the worst of
# the three states: Razorpay takes the guest's money, fires the confirmation
# webhook, and RazorpayService rejects it because it now fails closed rather
# than falling back to the placeholder literal published in this repo. The
# guest is charged and the booking never confirms. Refuse the deploy instead.
if grep -q '^RAZORPAY_KEY_ID=' /etc/quadis/api.env; then
  if ! grep -q '^RAZORPAY_WEBHOOK_SECRET=' /etc/quadis/api.env; then
    echo "FATAL: RAZORPAY_KEY_ID is configured but /quadis/razorpay-webhook-secret is not." >&2
    echo "       Guests would be charged and their bookings would never confirm." >&2
    echo "       aws ssm put-parameter --name /quadis/razorpay-webhook-secret \\" >&2
    echo "         --type SecureString --value '<the secret from the Razorpay dashboard>' \\" >&2
    echo "         --region $REGION" >&2
    exit 1
  fi
  # Not fatal — a test key is legitimate while rehearsing. But it must be loud,
  # because the symptom is a checkout that looks perfect and moves no money.
  if ! grep -q '^RAZORPAY_KEY_ID=rzp_live_' /etc/quadis/api.env; then
    echo "    WARNING: RAZORPAY_KEY_ID is not an rzp_live_ key." >&2
    echo "             The API will stay in simulated mode under NODE_ENV=production." >&2
  else
    echo "    razorpay: live key + webhook secret present"
  fi
fi

# The Groq/Gemini key is optional to the extent that the API still boots without it —
# but the chat assistant then answers every visitor with the same canned
# greeting at HTTP 200, which reads as "working" from the outside. The loop
# above drops absent parameters silently, so say something here.
if grep -qE '^(GEMINI|GROQ)_API_KEY(S)?=' /etc/quadis/api.env; then
  echo "    ai: key present — chat assistant is live"
else
  echo "    WARNING: /quadis/gemini-api-key or groq-api-key is missing." >&2
  echo "             The chat assistant will reply with canned text." >&2
  echo "             aws ssm put-parameter --name /quadis/gemini-api-key \\" >&2
  echo "               --type SecureString --value '<key>' --region $REGION" >&2
fi

# --- nginx ----------------------------------------------------------------
mkdir -p /etc/nginx/snippets
cp "$HERE/nginx/legacy-redirects.conf" /etc/nginx/snippets/legacy-redirects.conf
cp "$HERE/nginx/security-headers.conf" /etc/nginx/snippets/security-headers.conf
cp "$HERE/nginx/quadis.conf"           /etc/nginx/conf.d/quadis.conf

# Webroot for the Let's Encrypt HTTP-01 challenge. quadis.conf serves
# /.well-known/acme-challenge/ from here and deploy/cutover.sh authenticates
# with `-a webroot -w /var/www/certbot`. It must exist BEFORE cutover, and it
# stays empty except while a challenge is in flight — if the directory is
# missing, certbot fails at the one moment DNS has already moved.
mkdir -p /var/www/certbot/.well-known/acme-challenge

# Set the modes EXPLICITLY. This script runs under `umask 077` from the secrets
# section above, so the mkdir alone produces 0700 root-owned directories and a
# 0600 file — which nginx, running as the `nginx` user, cannot traverse. The
# challenge then 404s even though the file is on disk, and certbot --webroot
# writes its tokens into this same directory, so the certificate would fail on
# cutover day. Caught on the 31 Jul deploy by the canary below; do not remove
# these chmods or make them depend on umask state set by another section.
chmod 755 /var/www/certbot \
          /var/www/certbot/.well-known \
          /var/www/certbot/.well-known/acme-challenge

# A canary, so "is the challenge path reachable" is answerable BEFORE DNS moves
# rather than discovered during cutover. Both failure modes this guards against
# return 404 — the dotfile deny rule swallowing /.well-known, and an empty
# webroot — so a status code alone cannot tell them apart. A known body can.
# deploy/cutover.sh --check fetches this on both hostnames. Harmless to leave:
# it is a static string, and Let's Encrypt only ever fetches its own tokens.
echo "acme-ok" > /var/www/certbot/.well-known/acme-challenge/ping
chmod 644 /var/www/certbot/.well-known/acme-challenge/ping

# bootstrap.sh wrote a stub with the same server_name; two default_server
# blocks is a hard nginx error.
rm -f /etc/nginx/conf.d/default.conf

# Assert the redirects are actually present. bootstrap.sh `touch`es this file
# empty, and an empty include is silently valid — which is exactly how all 63
# legacy URLs would 404 while every check stayed green.
# 16 location blocks cover her 63 indexed URLs — the 52 room pages collapse
# into 8 per-hotel regexes, so rule count and URL count are not the same
# number. Verified 31 Jul. The floor is deliberately below 16 so adding or
# merging a rule does not trip it; it exists to catch an EMPTY file, not to
# police the exact count.
RULES="$(grep -c '^\s*location' /etc/nginx/snippets/legacy-redirects.conf || echo 0)"
if [ "$RULES" -lt 10 ]; then
  echo "FATAL: legacy-redirects.conf has only $RULES rules — expected 16." >&2
  echo "       Refusing to install; her indexed URLs would 404." >&2
  exit 1
fi
echo "    legacy redirect rules: $RULES"

# Re-apply TLS, because the copy above just deleted it.
#
# This script copies our quadis.conf over /etc/nginx/conf.d/quadis.conf on every
# deploy. certbot --nginx writes its `listen 443 ssl` and ssl_certificate lines
# INTO THAT SAME FILE at cutover — so every deploy after go-live silently
# removed them. nginx came back healthy, /healthz returned 200 over HTTP, the
# API was fine, push.sh printed "Deploy complete", and HTTPS was simply gone.
# Verified 1 Aug 2026: a routine deploy took the live site off HTTPS entirely
# while every check stayed green. The file's own header says do not hand-edit
# on the box because the next deploy overwrites it — nobody accounted for
# certbot being the thing doing the editing.
#
# `certbot install` re-deploys an EXISTING certificate into the config. It makes
# no ACME request, so it cannot fail validation or spend a rate limit, and it is
# skipped entirely before the first certificate exists.
if [ -d /etc/letsencrypt/live/quadishotels.com ]; then
  if certbot install --nginx --cert-name quadishotels.com \
       --non-interactive --redirect >/dev/null 2>&1; then
    echo "    TLS re-applied to nginx config"
  else
    echo "FATAL: certificate exists but could not be re-applied — HTTPS would be DOWN." >&2
    exit 1
  fi
fi

# Certificate auto-renewal.
#
# On Amazon Linux 2023 the certbot package ships `certbot-renew.timer`
# DISABLED. Issuing a certificate does not enable it, and `certbot renew
# --dry-run` passes happily either way — so every check looks green while
# nothing is scheduled to actually renew. Found on 1 Aug 2026, hours after
# go-live: the certificate was valid until 30 Oct and the site would simply
# have stopped answering HTTPS that day with no warning.
#
# Enabled here rather than by hand so a rebuilt box cannot lose it. Harmless
# before a certificate exists — renew is a no-op with nothing to renew.
systemctl enable --now certbot-renew.timer 2>/dev/null \
  && echo "    certbot renewal timer: enabled" \
  || echo "    WARNING: could not enable certbot-renew.timer — renewal is NOT scheduled" >&2

nginx -t

# --- services -------------------------------------------------------------
cp "$HERE/systemd/quadis-api.service" /etc/systemd/system/quadis-api.service
systemctl daemon-reload
systemctl enable quadis-api
systemctl restart quadis-api
systemctl reload nginx || systemctl restart nginx

# --- verify ---------------------------------------------------------------
# "Ready is not working" — AGENTS.md rule 5. Prove it answers before claiming
# the deploy succeeded.
echo "==> Verifying"
sleep 4
ok=0
for i in $(seq 1 15); do
  if curl -fsS -m 5 http://127.0.0.1:3001/api/health >/dev/null 2>&1 \
     || curl -fsS -m 5 http://127.0.0.1:3001/health >/dev/null 2>&1; then
    ok=1; break
  fi
  sleep 2
done

if [ "$ok" -ne 1 ]; then
  # Distinguish "nothing is listening" from "it answered, and told us it is
  # broken". /api/health returns 503 degraded when Postgres is unreachable or
  # when the app fell back to in-memory on production — curl -f treats that as
  # failure, correctly, but "did not answer" would send the next person after a
  # dead process when the process is fine and its database is not.
  BODY="$(curl -sS -m 5 http://127.0.0.1:3001/api/health 2>/dev/null || true)"
  if [ -n "$BODY" ]; then
    echo "FAIL: the API answered but reported itself unhealthy:" >&2
    echo "      $BODY" >&2
  else
    echo "FAIL: API did not answer on 127.0.0.1:3001" >&2
  fi
  systemctl --no-pager --lines=30 status quadis-api >&2 || true
  tail -30 /var/log/quadis-api.log >&2 || true
  exit 1
fi

curl -fsS -m 5 http://127.0.0.1/healthz >/dev/null && echo "    nginx  ok"
echo "    api    ok"
echo "    NODE_ENV=$(systemctl show quadis-api -p Environment --value | tr ' ' '\n' | grep NODE_ENV || echo MISSING)"
echo "==> Deploy complete"
